### ISSUE TITLE
请问一下,同时读取多个串口,该如何操作

### ISSUE THREAD

**Issue by daochushilang** [F1ReKing/Android-SerialPort#1]
请问一下同时打开两个串口，应该怎么区分数据，现在有数据混乱的现象，还有，如果我想要两个串口同时读取和接收数据，这部分代码应该怎么写呀？

**Comment by F1ReKing** [comment]
> 请问一下同时打开两个串口，应该怎么区分数据，现在有数据混乱的现象，还有，如果我想要两个串口同时读取和接收数据，这部分代码应该怎么写呀？

因为不是单例，所以可以写两个SerialPortHelper实例去做区分，我在项目应用中是这样用的，没啥问题

**Comment by daochushilang** [comment]
你好，能看看这部分的代码吗？接收数据的时候怎么区分的

**Comment by F1ReKing** [comment]
@daochushilang 不同的数据设置不同的回调区分   OnSerialPortDataListener这个监听回调

**Comment by daochushilang** [comment]
你好，请问博主有demo可以看看吗？第一次弄这个，不知道要怎么做，万分感谢

**Comment by MagicZhang1-ctrl** [comment]
@daochushilang 请问您最后解决多个串口读取数据的问题了吗？可以分享一下您的demo或者开发思路吗？
