### ISSUE TITLE
sendHex(String hex)方法异常

### ISSUE THREAD

**Issue by lmlate** [F1ReKing/Android-SerialPort#3]
ByteUtils中Hex转ByteArray数组越界 @F1ReKing

**Comment by F1ReKing** [comment]
@lmlate 是哪个版本  能否给下测试数据

**Comment by lmlate** [comment]
1.2.2版本，随意一串hex数据，hexToByteArr这个都会抛异常

**Comment by F1ReKing** [comment]
> 1.2.2版本，随意一串hex数据，hexToByteArr这个都会抛异常
用最新版本1.3.2看看

**Comment by F1ReKing** [comment]
@lmlate 用最新版本1.3.2 看看

**Comment by lmlate** [comment]
一样的问题，public static byte[] hexToByteArr(String hex)中最后的循环边界 i的增量应该为 i+=2就没有问题了
![ss](https://user-images.githubusercontent.com/27610944/70014956-ffea5580-15b6-11ea-996f-bc6fa45d9f30.png)

**Comment by lmlate** [comment]
一样的问题，是ByteUtils中hexToByteArr方法最后循环的问题，把i增量改为2就没问题了
![ss](https://user-images.githubusercontent.com/27610944/70015092-59528480-15b7-11ea-9b3d-b68ba9a4a9b2.png)

**Comment by F1ReKing** [comment]
@lmlate 是的 就是这个问题，感谢反馈
