### ISSUE TITLE
如果我不想引用androidX的library该怎样用？

### ISSUE THREAD

**Issue by dongweiq** [F1ReKing/Android-SerialPort#4]
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-20:19 to override.

如上所述，我把tools:replace="android:appComponentFactory加入到application节点后提示我要使用androidx，但是原有的项目都是用的support，所以不能容易的转为androidx，因为我看到串口操作并不需要androidx的内容，这个是不是可以隔离开啊

**Comment by F1ReKing** [comment]
@dongweiq 不好意思 才刚看到 我会剔除掉androidx 重新上传库

**Comment by F1ReKing** [comment]
@dongweiq  请使用最新版本1.6.0  我已移除androidx
